### ISSUE TITLE
Develop structure for authorization system

### ISSUE THREAD

**Issue by Zenexer** [massbay-cs/cs225-proj4#71]
See https://github.com/massbay-cs/cs225-proj4/wiki/Authorization

Decide how we should go about enforcing authorization levels and program any overarching classes.

**Comment by dewskii** [comment]
Saw this, Slightly confused on what I should be doing. what documentation should I be providing? and should I write an authentication manager? Login manager? I'm assuming the Users table will have a level column, admin's being 1, committee leaders 2, etc.

**Comment by dewskii** [comment]
@Zenexer

**Comment by Zenexer** [comment]
@dewskii Right now, focus on enforcing permissions rather than authenticating users.  The linked issues above will be coding using whatever documentation you provide.  As a very simple example, you could create a PermissionsManager class.  You don't need to have fully functional code, but there should be enough information available for other people to start on their assigned tasks.  For example, an interface for each class you plan to make would be helpful.

**Comment by dewskii** [comment]
added folder in the db directory for authorization and documentation on a unix style ACL
