### ISSUE TITLE
Enforce restrictions for Organizers -> Committee Leaders authorization level

### ISSUE THREAD

**Issue by Zenexer** [massbay-cs/cs225-proj4#73]
## Checklist
- [x] Step 1: Document restrictions for authorization level
- [x] Complete issue #71 (finished by David and Paul)
- [x] Step 2: Code restrictions for authorization level in corresponding Level subclass
## Step 1

See https://github.com/massbay-cs/cs225-proj4/wiki/Authorization for the information that Prof. Moussavi has provided about authorization/privileges.

I sent an email on Friday explaining the first step.  For convenience, here's what the email said:

By Sunday night at midnight: Add a comment in your issue listing the restrictions that your privilege level should have for each field in each table (except the rootkey table, which we're removing).

Here's an example of what that last step should look like for a few fields if your assigned privilege level is Organizers -> Admins:
- users table
  - level field
    - Can modify for other users
    - Can view for self, but not modify; this prevents a situation where there are no admins
  - fname field
    - Can modify for self
    - Can view for other users, but not modify
  - pwd field
    - Can modify for self, but not view
    - Can modify for other users, but not view; this allows admins to reset passwords
## Step 2

**Questions due by: Monday at 3 PM**
**Code due by: Tuesday at noon**

Now we need to take the data you've collected and turn it into code.  I've created a class for each privilege level in the `auth.levels` package.  Find the class that corresponds with your issue and develop the class.

Here's how permissions work:
1. When an operation is in progress, the backend calls the `Permissions#checkPermission` method with information about the requested operation.  It expects that if the operation is in violation of the user's permissions, checkPermission will throw an AuthorizationException.
2. The Permissions class looks up the privilege level of the current user and obtains an instance of the corresponding Level subclass.
3. The Permissions class calls one of the `checkPermission*` methods in the Level subclass named according to the table the operation affects.  For example, user-related operations call `checkPermissionUsers` because the user table is named `USERS`.  It passes a Context object as an argument.
4. Your Level subclass calls methods on the Context object to describe the restrictions your privilege level places on the particular table/field.

It's up to you to figure out:
1. How to use the Context class
2. How to implement the abstract methods from Level
3. How to ensure you cover all possible cases, without leaving any gaps for anyone to get through

There are some very basic examples in `auth.levels.LoggedOutLevel`.  You'll also want to take a close look at the `auth.levels.Level` and `auth.levels.Level.Context` classes.

**Important:**
- When you begin, IntelliJ should detect that your class is invalid.  You should see error indicators.
- When you are done, IntelliJ must not show any errors **or warnings** for your class.

Your task is not complete until:
- There are no warnings
- There are no errors
- All combinations of table/field are covered for your privilege level, except for UID fields, which aren't covered by permissions

IntelliJ tips:
- <kbd>F2</kbd> will jump to the next error.  If there aren't any more errors, it will jump to the next warning.
- <kbd>Alt</kbd> + <kbd>Enter</kbd> while the cursor is on an error/warning will provide options to automatically fix or aid in fixing the problem.  You can use this to automaticlaly generate a lot of code that would normally be tedious to write.
- The `InitDB` class has a list of all fields for each table.  Use <kbd>Ctrl/Cmd</kbd> + <kbd>O</kbd> to jump to a class by name.
- Fields are case-sensitive and will always be uppercase.

**Comment by bentheechidna** [comment]
- committeeTable
  - UID field
    - Cannot modify
  - title field
    - Can modify
  - chairman field
    - Cannot modify
  - members field
    - Cannot modify
  - tasks field
    - Can modify
  - income field
    - Cannot modify; Can view
  - expense field
    - Cannot modify; Can view
  - budget field
    - Cannot modify; Can view
- eventsTable
  - tableName
    - can modify
  - description field
    - can modify
  - details field
    - can modify
  - title field
    - can modify
  - startDate field
    - can modify
  - endDate field
    - can modify
  - complete field
    - can modify
  - street field
    - can modify
  - city field
    - can modify
  - state field
    - can modify
  - zipCode field
    - can modify
  - country field
    - can modify
  - organizerList field
    - cannot modify
  - subEventList
    - can modify
  - participantList
    - cannot modify
  - committee
    - cannot modify
- userTable
  - userId field
    - cannot modify
  - level field
    - cannot modify
  - fName field
    - cannot modify
  - lName field
    - cannot modify
  - PWD field
    - cannot modify
  - email field
    - cannot modify
  - phone field
    - cannot modify
  - street field
    - cannot modify
  - city field
    - cannot modify
  - state field
    - cannot modify
  - zipcode field
    - cannot modify
  - country field
    - cannot modify
  - participant field
    - cannot modify
  - eventLevel
    - cannot modify

**Comment by Zenexer** [comment]
@bentheechidna

**Questions due by: Monday at 3 PM**
**Code due by: Tuesday at noon**

See `Step 2` above.

**Comment by bentheechidna** [comment]
Got it. Starting now. Will get a list of questions asap should I have them.

**Comment by Zenexer** [comment]
@bentheechidna You still need a lot more code in your class.  Right now you're applying permissions blindly to entire tables; that's probably not what you want to do.  You need to have a switch statement for each like in the example and supply permissions for each field.

**Comment by bentheechidna** [comment]
Got it. On it.
