### ISSUE TITLE
Call checkPermission from EventSystem classes

### ISSUE THREAD

**Issue by Zenexer** [massbay-cs/cs225-proj4#86]
@dewskii

**Questions due by: Monday at 3 PM**
**Code due by: Tuesday at noon**
## Checklist
- [x] Step 1: Add `throws AuthorizationException` declarations to getters/setters
- [x] Step 2: Add `checkPermission` calls and fix related logical errors using `SystemTransaction`
## Description

There are a bunch of classes in the `BackEnd.EventSystem` package with getters and setters that need permission checks.  This is going to be a bit messy because there are times the setters are called when a permission check shouldn't occur.  I've started this task by adding permissions checks to `BackEnd.UserSystem.Participant` and `BackEnd.UserSystem.User`; you can use those as a reference.  Note that your code will only ever use the first two parameters of `checkPermission` because it will never need to deal with the `USERS` table.

The most immediately important aspect of this is that each getter and setter needs a `throws AuthorizationException` declaration.  I'd appreciate if you could add that to each of them **as soon as possible**, preferably tonight or early Monday, because it's going to have a significant impact on the frontend.  If it won't be possible for you to get that part done early, please let me know ASAP and I'll assign it to someone else.  (You'll still be responsible for the rest.)

There will definitely be places where the correct use of permission checks won't be straightforward.  For example, there are some constructors that are used to clone objects, and it doesn't make sense for them to throw AuthorizationExceptions.  In some cases, you can wrap those portions of the code in a try-with-resource block using a SystemTransaction; there's a good example of that in one of the constructors for User.  Within that try block, the permissions system will be bypassed and an AuthorizationException should never be thrown.  Often you can just avoid using the setters, but in that particular example the setter has some validation logic that needs to run.

**Comment by dewskii** [comment]
@Zenexer added the AuthorizationExceptions earlier this morning to the authorization branch, i'll push the finished code with the checkPermission calls later tonight or early tomorrow morning

**Comment by Zenexer** [comment]
@dewskii I'd appreciate if you could push the AuthorizationException declarations ASAP.  If it's mixed in with other changes, try to clean it up a bit and push what you have.  The frontend team needs it to do their part.

**Comment by dewskii** [comment]
@Zenexer added checkPermission calls in their respective areas, pushed the commits to backend
